{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yandex.android",
    "module": "mobileads",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "externalReleaseVariantExternalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobileads-8.2.0.aar",
          "url": "mobileads-8.2.0.aar",
          "size": 7923526,
          "sha512": "92ac5791272a2ecdc1eaa4e814b877659d09486d186685d421529893c794668cf50557ce0c370e34b62dbb69e05f776bcbf3958616779534ab058110a451e128",
          "sha256": "b19c223105b737671c9bc5419d53a562674afdfdfa42741f0b376562856761c5",
          "sha1": "b13c82f77add056eea2de851b56599441dbba1bb",
          "md5": "3107cdc719a8c93fafb571684ef52c25"
        }
      ]
    },
    {
      "name": "externalReleaseVariantExternalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics",
          "version": {
            "strictly": "[8.3.0,9.0.0)",
            "requires": "[8.3.0,9.0.0)",
            "prefers": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.yandex.varioqub",
          "module": "appmetrica-adapter",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "com.yandex.varioqub",
          "module": "analytic-adapter",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "androidx.fragment",
              "module": "fragment"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "androidx.fragment",
              "module": "fragment"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobileads-8.2.0.aar",
          "url": "mobileads-8.2.0.aar",
          "size": 7923526,
          "sha512": "92ac5791272a2ecdc1eaa4e814b877659d09486d186685d421529893c794668cf50557ce0c370e34b62dbb69e05f776bcbf3958616779534ab058110a451e128",
          "sha256": "b19c223105b737671c9bc5419d53a562674afdfdfa42741f0b376562856761c5",
          "sha1": "b13c82f77add056eea2de851b56599441dbba1bb",
          "md5": "3107cdc719a8c93fafb571684ef52c25"
        }
      ]
    }
  ]
}
