{
  "formatVersion": "1.1",
  "component": {
    "group": "io.appmetrica.analytics",
    "module": "analytics",
    "version": "8.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "binaryProdReleaseVariantBinaryProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-core-api",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-product-flow",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-8.5.1.aar",
          "url": "analytics-8.5.1.aar",
          "size": 1370830,
          "sha512": "22a2893b614d79a57019e60827656990eb549939ca2a0198f8e66797a0f043cf5860e60131ee1b6462ad5c5d834fe7e8538d493fd8f341346a98c3931b04ab4d",
          "sha256": "97205134ef274653490d307310e8b4b8b7d0857229ba37b8909f2641465d5ad5",
          "sha1": "e0425da9664eaf2f1b7ecd0ac2e8c0e6a8de9339",
          "md5": "3336b25ca62bd20930809888625efe61"
        }
      ]
    },
    {
      "name": "binaryProdReleaseVariantBinaryProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-ad-revenue",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-billing",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-id-sync",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-identifiers",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-location",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-remote-permissions",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-reporter-extension",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-screenshot",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-appsetid",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-core-utils",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-location-api",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-logger",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-modules-api",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-ndkcrashes-api",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-network-tasks",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-proto",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-core-api",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "io.appmetrica.analytics",
          "module": "analytics-product-flow",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-8.5.1.aar",
          "url": "analytics-8.5.1.aar",
          "size": 1370830,
          "sha512": "22a2893b614d79a57019e60827656990eb549939ca2a0198f8e66797a0f043cf5860e60131ee1b6462ad5c5d834fe7e8538d493fd8f341346a98c3931b04ab4d",
          "sha256": "97205134ef274653490d307310e8b4b8b7d0857229ba37b8909f2641465d5ad5",
          "sha1": "e0425da9664eaf2f1b7ecd0ac2e8c0e6a8de9339",
          "md5": "3336b25ca62bd20930809888625efe61"
        }
      ]
    }
  ]
}
